apiVersion: v1
kind: Route
metadata:
  name: registry-access
spec:
  host: 192.168.99.100.xip.io
  to:
    kind: Service
    name: docker-registry
    weight: 100
  port:
    targetPort: 5000-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
status:
  ingress:
    -
      host: 192.168.99.100.xip.io
      routerName: router
      conditions:
        -
          type: Admitted
          status: 'True'