kind: "DeploymentConfig"
apiVersion: "v1"
metadata:
  name: "es-master-2"
spec:
  template: 
    metadata:
      labels:
        name: "es-master-2"
    replicas: 1
    selector:
      name: "es-master-2"
    strategy: 
      type: "Rolling"
    spec:
      containers:
        - name: "es-master-2"
          image: "172.30.51.183:5000/elastic/elasticsearch:5.2.2"
          imagePullPolicy: "Always"
          limits:
            cpu:  400m
            memory: 1024Mi
          requests:
            cpu:    200m
            memory:   1024Mi
          ports:
            - name: http
              containerPort: 9200
              protocol: "TCP"
            - name: transport
              containerPort: 9300
              protocol: "TCP"
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: "CLUSTER_NAME"
              value: "elasticsearch"
            - name: "NUMBER_OF_MASTERS"
              value: "3"
            - name: NODE_MASTER
              value: "true"
            - name: NODE_INGEST
              value: "false"
            - name: NODE_DATA
              value: "true"
            - name: HTTP_ENABLE
              value: "true"
            - name: "ES_JAVA_OPTS"
              value: "-Xms512m -Xmx512m"
          volumeMounts:
            - name: storage
              mountPath: /data
      volumes:
        - name: "storage"
          emptyDir: {}